### ISSUE TITLE
css with not and nth-child

### ISSUE THREAD

**Issue by ashramwen** [Lonefy/vscode-JS-CSS-HTML-formatter#17]
if the css is `.state:not(:first-child)`,
it would be changed to `.state:not(: first-child)` after formatting.

a space is in front of 'first-child'.

**Comment by bitwiseman** [comment]
@ashramwen @Lonefy - fixed in the js-beautify 1.6.4.

**Comment by cheyneosy** [comment]
@bitwiseman I'm still having this issue with Sublime Text's version of this plugin. Have there been any fixes yet?

**Comment by bitwiseman** [comment]
@cheyneosy That would be something for the owner of the Sublime Text's version of this plugin could answer.  You can try your input (wrapped in a `<style>` tag) on http://jsbeautifier.org/ .
